describe('add territory', () => {
  beforeEach('loginAndAuth', () => {
    cy.checkPageLoadWithAuth('/admin/areas')
  })
  it('add territory valid', () => {
    //добавляем корректную территорию
    cy.get('[data-test="create-territory"]').click()
    cy.get('[data-vv-name="form.cadastralNumber"]').type('10:01:0010126:77')
    cy.get('[data-vv-name="form.region"]').click({ force: true })
    cy.get('[role="option"]').first().click()
    cy.get('[data-vv-name="form.address"]').type('Тестовый адрес')
    cy.get('[data-vv-name="form.category"]').click({ force: true }).wait(100)
    cy.get('.menuable__content__active [role="option"]').first().click({ force: true })
    cy.get('.leaflet-draw-draw-polygon').click()
    cy.get('.vue2leaflet-map').click().click('topRight').click('topLeft').click()
    cy.get('[data-vv-name="form.dimension"]').type('20000')
    cy.get('[data-vv-name="form.dimensionUnit"]').click({ force: true })
    cy.get('.menuable__content__active [role="option"]').first().click({ force: true })
    cy.get('[data-vv-name="form.ownership"]').click({ force: true })
    cy.get('.menuable__content__active [role="option"]').first().click({ force: true })
    cy.get('[data-vv-name="form.kindId"]').click({ force: true })
    cy.get('.menuable__content__active [role="option"]').first().click({ force: true })
    cy.get('#my-areas-admin-usage-form').find('[data-vv-name="form.optionId"]').click({ force: true })
    cy.get('.menuable__content__active [role="option"]').first().click({ force: true })
    cy.get('#my-areas-admin-usage-form [type="submit"]').click()
    cy.get('#my-areas-admin-transport-form').find('[data-vv-name="form.optionId"]').click({ force: true })
    cy.get('.menuable__content__active [role="option"]').first().click({ force: true })
    cy.get('[data-vv-name="form.transport-description"]').type('Тестовая транспортная инфраструктура')
    cy.get('#my-areas-admin-transport-form [type="submit"]').click()
    cy.get('#my-areas-admin-engineering-form').find('[data-vv-name="form.optionId"]').click({ force: true })
    cy.get('.menuable__content__active [role="option"]').first().click({ force: true })
    cy.get('[data-vv-name="form.engineering-description"]').type('Тестовая инженерная инфраструктура')
    cy.get('#my-areas-admin-engineering-form [type="submit"]').click()
    cy.get('[data-vv-name="form.description"]').type('Тестовое описание территории')
    cy.get('[data-vv-name="form.acquisition"]').click({ force: true })
    cy.get('.menuable__content__active [role="option"]').first().click({ force: true })
    cy.get('[data-vv-name="form.buildings"]').type('Тестовые существующие строения')
    cy.get('[data-vv-name="form.cadastralCost"]').type('10000')
    cy.get('[data-vv-name="form.cost"]').type('5000')
    cy.get('[data-vv-name="form.contacts"]').click({ force: true })
    cy.get('.menuable__content__active [role="option"]').first().click({ force: true })
    cy.get('[data-vv-name="form.remark"]').type('Тестовый комментарий')
    cy.intercept('POST', `api/area`).as('postArea')
    cy.get('[data-test="submit-btn"]').click().wait(200)
    cy.wait('@postArea')
    //проверяем, что территория добавлена
    cy.get('.my-areas-admin-table-view').should('have.length', 4).contains('10:01:0010126:77')
  })
})