describe('test adding user', () => {
  before('DBreset', () => {
    cy.resetDB()
  })
  beforeEach('loginAndAuth', () => {
    cy.checkPageLoadWithAuth('/admin/users')
  })
  after('DBreset', () => {
    cy.resetDB()
  })
  it.only('adding valid user', () => {
    cy.get('[data-test="create-user"]').click({ force: true })
    cy.get('[data-vv-name="form.lastname"]').should('be.visible').type('Тестовая фамилия')
    cy.get('[data-vv-name="form.firstname"]').type('Тестовое имя')
    cy.get('[data-vv-name="form.secondname"]').type('Тестовое отчество')
    cy.get('[data-vv-name="password"]').type('123456789')
    cy.get('[data-vv-name="form.phone"]').type('555555')
    cy.get('[data-vv-name="form.email"]').type('test@test.ru')
    cy.get('[data-vv-name="form.post"]').type('Тестовая должность')
    cy.get('[data-vv-name="form.role"]').click({ force: true })
    cy.get('.menuable__content__active .v-list-item').first().click()
    cy.get('[data-test="dialog"]').click()
    cy.get('[data-vv-name="form.active"]').click({ force: true })
    cy.get('.menuable__content__active .v-list-item').first().click()
    cy.get('[data-test="submit-btn"]').click({ force: true })
    cy.contains('Тестовая фамилия').should('be.visible')
  })
  it('adding user fails', () => {
    cy.get('[data-test="create-user"]').click()
    cy.get('[data-test="submit-btn"]').click()
    cy.get('[data-vv-name="form.lastname"]').parent().parent().parent().parent().should('have.class', 'v-input--has-state')
    cy.get('[data-vv-name="form.firstname"]').parent().parent().parent().parent().should('have.class', 'v-input--has-state')
    cy.get('[data-vv-name="form.secondname"]').parent().parent().parent().parent().should('have.class', 'v-input--has-state')
    cy.get('[data-vv-name="password"]').parent().parent().parent().parent().should('have.class', 'v-input--has-state')
    cy.get('[data-vv-name="form.phone"]').parent().parent().parent().parent().should('have.class', 'v-input--has-state')
    cy.get('[data-vv-name="form.email"]').parent().parent().parent().parent().should('have.class', 'v-input--has-state')
    cy.get('[data-vv-name="form.post"]').parent().parent().parent().parent().should('have.class', 'v-input--has-state')
    cy.get('[data-vv-name="form.role"]').parent().parent().parent().parent().parent().should('have.class', 'v-input--has-state')
    cy.get('[data-vv-name="form.active"]').parent().parent().parent().parent().parent().should('have.class', 'v-input--has-state')
  })
  it('test cancel btn', () => {
    cy.get('.v-dialog__content.v-dialog__content--active').should('not.exist')
    cy.get('[data-test="create-user"]').click()
    cy.get('.v-dialog__content.v-dialog__content--active').should('exist')
    cy.get('[data-test="close-btn"]').click()
    cy.get('.v-dialog__content.v-dialog__content--active').should('not.exist')
  })
  it('test close btn icon', () => {
    cy.get('.v-dialog__content.v-dialog__content--active').should('not.exist')
    cy.get('[data-test="create-user"]').click()
    cy.get('.v-dialog__content.v-dialog__content--active').should('exist')
    cy.get('[data-test="close-btn-icon"]').click()
    cy.get('.v-dialog__content.v-dialog__content--active').should('not.exist')
  })
  it('test email tip', () => {
    cy.get('[data-test="create-user"]').click()
    cy.get('[data-vv-name="form.email"]').type('tst')
    cy.get('[data-vv-name="form.email"]').parent().parent().parent().parent().should('have.class', 'v-input--has-state')
  })
  it('test password tip1', () => {
    cy.get('[data-test="create-user"]').click()
    cy.get('[data-vv-name="password"]').type('123')
    cy.get('[data-vv-name="password"]').parent().parent().parent().parent().should('have.class', 'v-input--has-state')
  })
  it('test password tip2', () => {
    cy.get('[data-test="create-user"]').click()
    cy.get('[data-vv-name="password"]').type('121111111111111111')
    cy.get('[data-vv-name="password"]').parent().parent().parent().parent().should('have.class', 'v-input--has-state')
  })
})